# Generated by Django 4.2.25 on 2025-10-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyweatherdata',
            name='pressure',
        ),
    ]
