# Generated by Django 4.2.25 on 2025-10-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_remove_hourlyweatherdata_pressure'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hourlyweatherdata',
            constraint=models.UniqueConstraint(fields=('location', 'date'), name='unique_location_date'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('locality',), name='unique_locality'),
        ),
    ]
